### ISSUE TITLE
CIDER 0.10 release plan

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#1243]
Below is a list of all the tickets we need to fix before CIDER 0.10 can be released:

- [x] #1242 Debugging overlay does not always display on the right line
- [x] #1222 Result overlay too prominent
- [x] #1217 Make it possible to associate a project folder with any connection
- [x] #1197 Display some indication that we're waiting for a result for long-running evaluations
- [x] #1177 TAB and RET navigation on *cider-test-report* buffers
- [ ] #1115 CIDER locks up when printing large strings

There's not that many of them, so I hope the release can happen in a couple of weeks. If we manage to squeeze more stuff in, that'd be great, and if we don't - tough luck. Let me know if you feel something else has to be part of the 0.10 release.

**Comment by Malabarba** [comment]
Ok, I'll do the overlay things.

**Comment by Malabarba** [comment]
I'll do the overlay things.

I would like to add, it would be really nice if we could optimize startup time a little, jack-in takes a couple of minutes on my laptop. It's not worth sacrificing features for it, but I think it's worth having a quick look to see if there's not some big stupid thing causing this.

**Comment by bbatsov** [comment]
See https://github.com/clojure-emacs/cider-nrepl/issues/218

That's definitely a serious problem, but I don't think it has an easy solution. The tradeoff from using mranderson - we got dep isolation, but the startup time became epic.

**Comment by bbatsov** [comment]
I plan to work on #1217 for starters. I hope more people will pitch in to help with the rest of the tickets.

**Comment by bbatsov** [comment]
With all the recent development this issue doesn't make much sense anymore.
