### ISSUE TITLE
CIDER 1.2

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/cider#3090]
Just a meta issue to track the remaining work for upcoming CIDER 1.2 release. Here's how I see things:

* [x] Cut nREPL 0.9
* [x] #3088 (related to nREPL 0.9)
* [ ] #3061 (add basic support for nbi)

Those are simple things that would probably be nice to do as well:

* [ ] #3055 
* [ ] #3076 

Everyone's welcome to add to this list. //cc @plexus @vemv If the final scope gets bigger I'll create a milestone in GitHub as well.

**Comment by vemv** [comment]
I find these easy / important:

https://github.com/clojure-emacs/orchard/pull/138
https://github.com/clojure-emacs/enrich-classpath/issues/5
https://github.com/clojure-emacs/cider-nrepl/pull/725

**Comment by bendlas** [comment]
For unix domain sockets on more recent JDK.

- [ ] [ClassCastException raised when connecting to nREPL server via nrepl+unix](https://github.com/nrepl/nrepl/issues/245)

**Comment by bendlas** [comment]
Found another ClassCastException related to unix domain socket in CIDER middlware

- [ ] https://github.com/clojure-emacs/cider-nrepl/issues/727
